// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4579.FinalProject.commands;

import edu.wpi.first.wpilibj.DriverStationLCD;
import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc4579.FinalProject.Robot;
import org.usfirst.frc4579.FinalProject.RobotMap;

/**
 *
 */
public class AutonomousCG extends CommandGroup {

    DriverStationLCD dslcd;

    public AutonomousCG() {
        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.
        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        if (this.isRunning()) {
            System.out.println("....Starting Autonomous.");
            RobotMap.driveTrainRobotDrive41.setSafetyEnabled(false);
        }
        if (Robot.useCamera) {
            if (this.isRunning()) {
                dslcd.println(DriverStationLCD.Line.kUser1, 1, "Acquiring Camera Image.");
            }
            addSequential(new AutonomousInit());
        }
        addSequential(new MoveForward());
        addSequential(new ToroShootAngle());
        addSequential(new Reload());
        addSequential(new ShootIfHot());
        if (this.isRunning()) {
            System.out.println("....Ending Autonomous.");
        }
    }
}
