// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4579.FinalProject.commands;

import edu.wpi.first.wpilibj.DriverStationLCD;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4579.FinalProject.Robot;

/**
 *
 */
public class MoveForward extends Command {

    DriverStationLCD lcd;

//    protected synchronized void setInterruptible(boolean interruptible) {
//        super.setInterruptible(interruptible); //To change body of generated methods, choose Tools | Templates.
//    }

    public MoveForward() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
        this.setInterruptible(false);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        //lcd = DriverStationLCD.getInstance();
        //lcd.println(DriverStationLCD.Line.kUser2, 1, "Moving Forward.");
        System.out.println("......Starting MoveForward.");
        setTimeout(2.5);
        Robot.driveTrain.move();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.driveTrain.move();
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        //return (Robot.driveTrain.getRange() < 9.0 || isTimedOut());
        return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.stop();
        System.out.println("......Ending MoveForward.");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
