// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4579.FinalProject.commands;

import edu.wpi.first.wpilibj.DriverStationLCD;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4579.FinalProject.Robot;

/**
 *
 */
public class ToroShootAngle extends Command {

    int setpoint;
    DriverStationLCD lcd;

    public ToroShootAngle() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.elevator);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
        lcd = DriverStationLCD.getInstance();
        lcd.println(DriverStationLCD.Line.kUser3, 1, "Lowering Rollers.");
        System.out.println("......Starting ToroShootAngle.");
        setTimeout(5.0);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.elevator.tilt(-1.0);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut() || (Robot.elevator.getEncoderCount() <= -86.5);
    }

    // Called once after isFinished returns true
    protected void end() {
        Robot.elevator.stop();
        System.out.println("......Ending ToroShootAngle.");
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
